### ISSUE TITLE
After running the exe file, this error appears

### ISSUE THREAD

**Issue by StewedLawyer9** [amamic1803/Autofish-Fishing-Planet#23]
Traceback (most recent call last):
  File "main.py", line 2, in <module>
    import autofish
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "autofish\__init__.py", line 1, in <module>
    from runner import run
ModuleNotFoundError: No module named 'runner'

**Comment by amamic1803** [comment]
Yes, that was at the time when I was doing some work and code wasn't complete. If you try to build it now, it should open just fine. I need to update templates for the bot to work, but I won't have the time to do that for the next month. Come back here sometime in July, there should be a new working release published by then.
